name: build

on:
  pull_request:
  push:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: share
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: /home/runner/work/cli-share-file/cli-share-file